package com.github.xdptdr.mbwar.jms.notes;

import javax.jms.BytesMessage;
import javax.jms.CompletionListener;
import javax.jms.Connection;
import javax.jms.ConnectionConsumer;
import javax.jms.ConnectionFactory;
import javax.jms.ConnectionMetaData;
import javax.jms.DeliveryMode;
import javax.jms.Destination;
import javax.jms.ExceptionListener;
import javax.jms.IllegalStateException;
import javax.jms.IllegalStateRuntimeException;
import javax.jms.JMSConnectionFactory;
import javax.jms.JMSConnectionFactoryDefinition;
import javax.jms.JMSConnectionFactoryDefinitions;
import javax.jms.JMSDestinationDefinition;
import javax.jms.JMSDestinationDefinitions;
import javax.jms.JMSException;
import javax.jms.JMSPasswordCredential;
import javax.jms.JMSProducer;
import javax.jms.JMSRuntimeException;
import javax.jms.JMSSecurityException;
import javax.jms.JMSSecurityRuntimeException;
import javax.jms.JMSSessionMode;
import javax.jms.MapMessage;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.MessageEOFException;
import javax.jms.MessageFormatException;
import javax.jms.MessageFormatRuntimeException;
import javax.jms.MessageListener;
import javax.jms.MessageNotReadableException;
import javax.jms.MessageNotWriteableException;
import javax.jms.MessageNotWriteableRuntimeException;
import javax.jms.MessageProducer;
import javax.jms.ObjectMessage;
import javax.jms.Queue;
import javax.jms.QueueBrowser;
import javax.jms.QueueConnection;
import javax.jms.QueueConnectionFactory;
import javax.jms.QueueReceiver;
import javax.jms.QueueSender;
import javax.jms.QueueSession;
import javax.jms.ResourceAllocationException;
import javax.jms.ResourceAllocationRuntimeException;
import javax.jms.ServerSession;
import javax.jms.ServerSessionPool;
import javax.jms.Session;
import javax.jms.StreamMessage;
import javax.jms.TemporaryTopic;
import javax.jms.TextMessage;
import javax.jms.Topic;
import javax.jms.TopicConnection;
import javax.jms.TopicConnectionFactory;
import javax.jms.TopicPublisher;
import javax.jms.TopicRequestor;
import javax.jms.TopicSession;
import javax.jms.TopicSubscriber;
import javax.jms.TransactionInProgressException;
import javax.jms.TransactionInProgressRuntimeException;
import javax.jms.TransactionRolledBackException;
import javax.jms.TransactionRolledBackRuntimeException;
import javax.jms.XAQueueConnection;
import javax.jms.XAQueueConnectionFactory;
import javax.jms.XAQueueSession;
import javax.jms.XASession;
import javax.jms.XATopicConnection;
import javax.jms.XATopicConnectionFactory;
import javax.jms.XATopicSession;

import com.github.xdptdr.mbwar.jaxrs.notes.N;

public class Notes {

	public static void notes(N n) {
		n.todo(BytesMessage.class);
		n.todo(CompletionListener.class);
		n.todo(Connection.class);
		n.todo(ConnectionConsumer.class);
		n.todo(ConnectionFactory.class);
		n.todo(ConnectionMetaData.class);
		n.todo(DeliveryMode.class);
		n.todo(Destination.class);
		n.todo(ExceptionListener.class);
		n.todo(IllegalStateException.class);
		n.todo(IllegalStateRuntimeException.class);
		n.todo(JMSConnectionFactory.class);
		n.todo(JMSConnectionFactoryDefinition.class);
		n.todo(JMSConnectionFactoryDefinitions.class);
		n.todo(JMSDestinationDefinition.class);
		n.todo(JMSDestinationDefinitions.class);
		n.todo(JMSException.class);
		n.todo(JMSPasswordCredential.class);
		n.todo(JMSProducer.class);
		n.todo(JMSRuntimeException.class);
		n.todo(JMSSecurityException.class);
		n.todo(JMSSecurityRuntimeException.class);
		n.todo(JMSSessionMode.class);
		n.todo(MapMessage.class);
		n.todo(Message.class);
		n.todo(MessageConsumer.class);
		n.todo(MessageEOFException.class);
		n.todo(MessageFormatException.class);
		n.todo(MessageFormatRuntimeException.class);
		n.todo(MessageListener.class);
		n.todo(MessageNotReadableException.class);
		n.todo(MessageNotWriteableException.class);
		n.todo(MessageNotWriteableRuntimeException.class);
		n.todo(MessageProducer.class);
		n.todo(ObjectMessage.class);
		n.todo(Queue.class);
		n.todo(QueueBrowser.class);
		n.todo(QueueConnection.class);
		n.todo(QueueConnectionFactory.class);
		n.todo(QueueReceiver.class);
		n.todo(QueueSender.class);
		n.todo(QueueSession.class);
		n.todo(ResourceAllocationException.class);
		n.todo(ResourceAllocationRuntimeException.class);
		n.todo(ServerSession.class);
		n.todo(ServerSessionPool.class);
		n.todo(Session.class);
		n.todo(StreamMessage.class);
		n.todo(TemporaryTopic.class);
		n.todo(TextMessage.class);
		n.todo(Topic.class);
		n.todo(TopicConnection.class);
		n.todo(TopicConnectionFactory.class);
		n.todo(TopicPublisher.class);
		n.todo(TopicRequestor.class);
		n.todo(TopicSession.class);
		n.todo(TopicSubscriber.class);
		n.todo(TransactionInProgressException.class);
		n.todo(TransactionInProgressRuntimeException.class);
		n.todo(TransactionRolledBackException.class);
		n.todo(TransactionRolledBackRuntimeException.class);
		n.todo(XAQueueConnection.class);
		n.todo(XAQueueConnectionFactory.class);
		n.todo(XAQueueSession.class);
		n.todo(XASession.class);
		n.todo(XATopicConnection.class);
		n.todo(XATopicConnectionFactory.class);
		n.todo(XATopicSession.class);
	}

	public static void main(String[] args) {
		N n = new N();
		notes(n);
		n.sumUp();
	}
}
