package com.github.xdptdr.notes.persistence;

import javax.persistence.*;
import javax.persistence.criteria.AbstractQuery;
import javax.persistence.criteria.CollectionJoin;
import javax.persistence.criteria.CommonAbstractCriteria;
import javax.persistence.criteria.CompoundSelection;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.CriteriaUpdate;
import javax.persistence.criteria.Expression;
import javax.persistence.criteria.Fetch;
import javax.persistence.criteria.FetchParent;
import javax.persistence.criteria.From;
import javax.persistence.criteria.Join;
import javax.persistence.criteria.JoinType;
import javax.persistence.criteria.ListJoin;
import javax.persistence.criteria.MapJoin;
import javax.persistence.criteria.Order;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Path;
import javax.persistence.criteria.PluralJoin;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import javax.persistence.criteria.Selection;
import javax.persistence.criteria.SetJoin;
import javax.persistence.criteria.Subquery;
import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.BasicType;
import javax.persistence.metamodel.Bindable;
import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.EmbeddableType;
import javax.persistence.metamodel.EntityType;
import javax.persistence.metamodel.IdentifiableType;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.ManagedType;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.MappedSuperclassType;
import javax.persistence.metamodel.Metamodel;
import javax.persistence.metamodel.PluralAttribute;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import javax.persistence.metamodel.Type;
import javax.persistence.spi.ClassTransformer;
import javax.persistence.spi.LoadState;
import javax.persistence.spi.PersistenceProvider;
import javax.persistence.spi.PersistenceProviderResolver;
import javax.persistence.spi.PersistenceProviderResolverHolder;
import javax.persistence.spi.PersistenceUnitInfo;
import javax.persistence.spi.PersistenceUnitTransactionType;
import javax.persistence.spi.ProviderUtil;

import com.github.xdptdr.notes.N;

public class Notes {

	private static void notes(N n) {

		n.todo(Access.class);
		n.todo(AccessType.class);
		n.todo(AssociationOverride.class);
		n.todo(AssociationOverrides.class);
		n.todo(AttributeConverter.class);
		n.todo(AttributeNode.class);
		n.todo(AttributeOverride.class);
		n.todo(AttributeOverrides.class);
		n.todo(Basic.class);
		n.todo(Cache.class);
		n.todo(Cacheable.class);
		n.todo(CacheRetrieveMode.class);
		n.todo(CacheStoreMode.class);
		n.todo(CascadeType.class);
		n.todo(CollectionTable.class);
		n.todo(Column.class);
		n.todo(ColumnResult.class);
		n.todo(ConstraintMode.class);
		n.todo(ConstructorResult.class);
		n.todo(Convert.class);
		n.todo(Converter.class);
		n.todo(Converts.class);
		n.todo(DiscriminatorColumn.class);
		n.todo(DiscriminatorType.class);
		n.todo(DiscriminatorValue.class);
		n.todo(ElementCollection.class);
		n.todo(Embeddable.class);
		n.todo(Embedded.class);
		n.todo(EmbeddedId.class);
		n.todo(Entity.class);
		n.todo(EntityExistsException.class);
		n.todo(EntityGraph.class);
		n.todo(EntityListeners.class);
		n.todo(EntityManager.class);
		n.todo(EntityManagerFactory.class);
		n.todo(EntityNotFoundException.class);
		n.todo(EntityResult.class);
		n.todo(EntityTransaction.class);
		n.todo(Enumerated.class);
		n.todo(EnumType.class);
		n.todo(ExcludeDefaultListeners.class);
		n.todo(ExcludeSuperclassListeners.class);
		n.todo(FetchType.class);
		n.todo(FieldResult.class);
		n.todo(FlushModeType.class);
		n.todo(ForeignKey.class);
		n.todo(GeneratedValue.class);
		n.todo(GenerationType.class);
		n.todo(Id.class);
		n.todo(IdClass.class);
		n.todo(Index.class);
		n.todo(Inheritance.class);
		n.todo(InheritanceType.class);
		n.todo(JoinColumn.class);
		n.todo(JoinColumns.class);
		n.todo(JoinTable.class);
		n.todo(Lob.class);
		n.todo(LockModeType.class);
		n.todo(LockTimeoutException.class);
		n.todo(ManyToMany.class);
		n.todo(ManyToOne.class);
		n.todo(MapKey.class);
		n.todo(MapKeyClass.class);
		n.todo(MapKeyColumn.class);
		n.todo(MapKeyEnumerated.class);
		n.todo(MapKeyJoinColumn.class);
		n.todo(MapKeyJoinColumns.class);
		n.todo(MapKeyTemporal.class);
		n.todo(MappedSuperclass.class);
		n.todo(MapsId.class);
		n.todo(NamedAttributeNode.class);
		n.todo(NamedEntityGraph.class);
		n.todo(NamedEntityGraphs.class);
		n.todo(NamedNativeQueries.class);
		n.todo(NamedNativeQuery.class);
		n.todo(NamedQueries.class);
		n.todo(NamedQuery.class);
		n.todo(NamedStoredProcedureQueries.class);
		n.todo(NamedStoredProcedureQuery.class);
		n.todo(NamedSubgraph.class);
		n.todo(NonUniqueResultException.class);
		n.todo(NoResultException.class);
		n.todo(OneToMany.class);
		n.todo(OneToOne.class);
		n.todo(OptimisticLockException.class);
		n.todo(OrderBy.class);
		n.todo(OrderColumn.class);
		n.todo(Parameter.class);
		n.todo(ParameterMode.class);
		n.todo(Persistence.class);
		n.todo(PersistenceContext.class);
		n.todo(PersistenceContexts.class);
		n.todo(PersistenceContextType.class);
		n.todo(PersistenceException.class);
		n.todo(PersistenceProperty.class);
		n.todo(PersistenceUnit.class);
		n.todo(PersistenceUnits.class);
		n.todo(PersistenceUnitUtil.class);
		n.todo(PersistenceUtil.class);
		n.todo(PessimisticLockException.class);
		n.todo(PessimisticLockScope.class);
		n.todo(PostLoad.class);
		n.todo(PostPersist.class);
		n.todo(PostRemove.class);
		n.todo(PostUpdate.class);
		n.todo(PrePersist.class);
		n.todo(PreRemove.class);
		n.todo(PreUpdate.class);
		n.todo(PrimaryKeyJoinColumn.class);
		n.todo(PrimaryKeyJoinColumns.class);
		n.todo(Query.class);
		n.todo(QueryHint.class);
		n.todo(QueryTimeoutException.class);
		n.todo(RollbackException.class);
		n.todo(SecondaryTable.class);
		n.todo(SecondaryTables.class);
		n.todo(SequenceGenerator.class);
		n.todo(SharedCacheMode.class);
		n.todo(SqlResultSetMapping.class);
		n.todo(SqlResultSetMappings.class);
		n.todo(StoredProcedureParameter.class);
		n.todo(StoredProcedureQuery.class);
		n.todo(Subgraph.class);
		n.todo(SynchronizationType.class);
		n.todo(Table.class);
		n.todo(TableGenerator.class);
		n.todo(Temporal.class);
		n.todo(TemporalType.class);
		n.todo(TransactionRequiredException.class);
		n.todo(Transient.class);
		n.todo(Tuple.class);
		n.todo(TupleElement.class);
		n.todo(TypedQuery.class);
		n.todo(UniqueConstraint.class);
		n.todo(ValidationMode.class);
		n.todo(Version.class);

		n.todo(AbstractQuery.class);
		n.todo(CollectionJoin.class);
		n.todo(CommonAbstractCriteria.class);
		n.todo(CompoundSelection.class);
		n.todo(CriteriaBuilder.class);
		n.todo(CriteriaDelete.class);
		n.todo(CriteriaQuery.class);
		n.todo(CriteriaUpdate.class);
		n.todo(Expression.class);
		n.todo(Fetch.class);
		n.todo(FetchParent.class);
		n.todo(From.class);
		n.todo(Join.class);
		n.todo(JoinType.class);
		n.todo(ListJoin.class);
		n.todo(MapJoin.class);
		n.todo(Order.class);
		n.todo(ParameterExpression.class);
		n.todo(Path.class);
		n.todo(PluralJoin.class);
		n.todo(Predicate.class);
		n.todo(Root.class);
		n.todo(Selection.class);
		n.todo(SetJoin.class);
		n.todo(Subquery.class);

		n.todo(Attribute.class);
		n.todo(BasicType.class);
		n.todo(Bindable.class);
		n.todo(CollectionAttribute.class);
		n.todo(EmbeddableType.class);
		n.todo(EntityType.class);
		n.todo(IdentifiableType.class);
		n.todo(ListAttribute.class);
		n.todo(ManagedType.class);
		n.todo(MapAttribute.class);
		n.todo(MappedSuperclassType.class);
		n.todo(Metamodel.class);
		n.todo(PluralAttribute.class);
		n.todo(SetAttribute.class);
		n.todo(SingularAttribute.class);
		n.todo(StaticMetamodel.class);
		n.todo(Type.class);

		n.todo(ClassTransformer.class);
		n.todo(LoadState.class);
		n.todo(PersistenceProvider.class);
		n.todo(PersistenceProviderResolver.class);
		n.todo(PersistenceProviderResolverHolder.class);
		n.todo(PersistenceUnitInfo.class);
		n.todo(PersistenceUnitTransactionType.class);
		n.todo(ProviderUtil.class);

	}

	public static void main(String[] args) {
		N n = new N();
		notes(n);
		n.sumUp();
	}

}
